#!/bin/bash

source "$CONFIG_DIR/colors.sh"
source "$CONFIG_DIR/padding.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

## bar appearance
sketchybar --bar    position=top            \
                    height=32               \
                    notch_display_height=38 \
                    notch_width=230         \
                    blur_radius=12          \
                    color=$COLOR_BAR        \
                    padding_left=12         \
                    padding_right=12

default=(
  padding_left=$MARGIN
  padding_right=$MARGIN
  icon.font="SF Pro:Medium:17.0"
  label.font="SF Pro:Expanded Medium:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=$PADDING_OUTER
  icon.padding_right=$PADDING_INNER
  label.padding_left=$PADDING_INNER
  label.padding_right=$PADDING_OUTER
  background.corner_radius=5
  background.height=24
)
condensed=(
  padding_left=$MARGIN
  padding_right=$MARGIN
  icon.font="IBM Plex Sans Condensed:Medium:17.0"
  label.font="IBM Plex Sans Condensed:Medium:16.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=$PADDING_OUTER
  icon.padding_right=$PADDING_INNER
  label.padding_left=$PADDING_INNER
  label.padding_right=$PADDING_OUTER
  background.corner_radius=0
  background.height=24
)
mono=(
  padding_left=$MARGIN
  padding_right=$MARGIN
  icon.font="IBM Plex Mono:Medium:17.0"
  label.font="IBM Plex Mono:Medium:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=$PADDING_OUTER
  icon.padding_right=$PADDING_INNER
  label.padding_left=$PADDING_INNER
  label.padding_right=$PADDING_OUTER
  background.corner_radius=0
  background.height=24
)

sketchybar --default "${default[@]}"


###################
## MENUBAR ITEMS ##
###################

sketchybar --add event aerospace_workspace_change

## left items
source $ITEM_DIR/aerospace.sh

# for sid in $(aerospace list-workspaces --all); do
#     sketchybar --add item space.old.$sid left \
#         --subscribe space.old.$sid aerospace_workspace_change \
#         --set space.old.$sid \
#         background.color=$COLOR_80 \
#         background.drawing=off \
#         icon.drawing=off \
#         label.padding_left=$PADDING_OUTER \
#         label.color=$COLOR_10 \
#         label="$sid" \
#         click_script="aerospace workspace $sid" \
#         script="$CONFIG_DIR/plugins/aerospace.sh $sid"
# done


## q items - left of notch
source $ITEM_DIR/front_app.sh


## right items
source "$ITEM_DIR/clock.sh"
# source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/battery_time_remaining.sh"


## force all scripts to run the first time (never do this in a script)
sketchybar --update
