#!/bin/bash

source "$CONFIG_DIR/colors.sh"

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar    position=top            \
                    height=32               \
                    notch_display_height=38 \
                    notch_width=230         \
                    blur_radius=12          \
                    color=$COLOR_BAR        \
                    padding_left=12         \
                    padding_right=12

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

export PADDING_OUTER=5
export PADDING_INNER=4
export MARGIN=2

default=(
  padding_left=$MARGIN
  padding_right=$MARGIN
  icon.font="SF Pro:Medium:17.0"
  label.font="SF Pro:Expanded Medium:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=$PADDING_OUTER
  icon.padding_right=$PADDING_INNER
  label.padding_left=$PADDING_INNER
  label.padding_right=$PADDING_OUTER
  background.corner_radius=5
  background.height=24
)
condensed=(
  padding_left=$MARGIN
  padding_right=$MARGIN
  icon.font="IBM Plex Sans Condensed:Medium:17.0"
  label.font="IBM Plex Sans Condensed:Medium:16.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=$PADDING_OUTER
  icon.padding_right=$PADDING_INNER
  label.padding_left=$PADDING_INNER
  label.padding_right=$PADDING_OUTER
  background.corner_radius=0
  background.height=24
)
mono=(
  padding_left=$MARGIN
  padding_right=$MARGIN
  icon.font="IBM Plex Mono:Medium:17.0"
  label.font="IBM Plex Mono:Medium:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=$PADDING_OUTER
  icon.padding_right=$PADDING_INNER
  label.padding_left=$PADDING_INNER
  label.padding_right=$PADDING_OUTER
  background.corner_radius=0
  background.height=24
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]}"
#     icon.padding_left=7
#     icon.padding_right=7
#     background.color=0x40ffffff
#     background.corner_radius=5
#     background.height=25
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.old.$sid left \
        --subscribe space.old.$sid aerospace_workspace_change \
        --set space.old.$sid \
        background.color=$COLOR_80 \
        background.drawing=off \
        icon.drawing=off \
        label.padding_left=$PADDING_OUTER \
        label.color=$COLOR_10 \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

# source $ITEM_DIR/aerospace.sh

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

# sketchybar --add item chevron left \
#            --set chevron icon=􀆊 label.drawing=off \
#            icon.padding_right=10
sketchybar --add item front_app q \
           --set front_app icon.drawing=off \
           label.padding_left=$PADDING_OUTER \
           script="$PLUGIN_DIR/front_app.sh" \
           background.color=$COLOR_80 \
           label.color=$COLOR_10 \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

source "$ITEM_DIR/clock.sh"
# source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
